live_config_reload = true

import = ["~/.config/alacritty/themes/themes/snazzy.toml"]

# 指定 Alacritty 启动时使用 Fish Shell
[shell]
program = "/Users/spkz/.nix-profile/bin/fish"
args = ["-l"]

[env]
TERM = "xterm-256color"

[font]
size = 12.5
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7
padding = { x = 20, y = 20 }
blur = true
