live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12
normal = { family = "JetbrainsMono Nerd Font" }

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85
padding = { x = 15, y = 15 }
blur = true
