live_config_reload = true 

import = [
    "~/.config/alacritty/themes/themes/snazzy.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0
normal = { family = "JetBrains Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[window]
#decorations = "Transparent"
decorations = "buttonless"
opacity = 0.80
padding = { x = 20, y = 20}


