live_config_reload = true 

#import = [
#    "~/.config/alacritty/themes/themes/snazzy.toml"
#]

[env]
TERM = "xterm-256color"

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.80
padding = { x = 20, y = 20}
blur = true
