live_config_reload = true 

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "Transparent"
dynamic_padding = false
dynamic_title = true
# opacity = 1
# blur = true

[window.padding]
x = 24
y = 32
