live_config_reload = true 

import = [
    "~/.config/alacritty/themes/themes/snazzy.toml"
]

[font]
size = 12.0
normal = { family = "JetBrains Mono", style = "Regular" }

[mouse]
hide_when_typing = true

[window]
decorations = "Transparent"
dynamic_padding = true
dynamic_title = true
#opacity = 0.6
#blur = true
padding = { x = 16, y = 32}
