format = "$directory[$git_branch](bold green) $all"

[directory]
truncation_length = 1
truncate_to_repo = true

[git_branch]
format = "\\[[$branch]($style)\\] "
style = "bold purple"

[package]
disabled = true

[bun]
disabled = true
