# vim:ft=kitty

## name: Cursor Dark
## author: Anysphere / iTerm2-Color-Schemes
## license: MIT
## blurb: Cursor IDE dark theme. Matches Ghostty's built-in Cursor Dark.

foreground              #d4d4d4
background              #141414
selection_foreground    #e4e4e4
selection_background    #2c2c2c

cursor                  #d4d4d4
cursor_text_color       #141414

url_color               #81a1c1

active_border_color     #81a1c1
inactive_border_color   #4a4a4a
bell_border_color       #fc6b83

active_tab_foreground   #d4d4d4
active_tab_background   #141414
inactive_tab_foreground #8a8a8a
inactive_tab_background #141414
tab_bar_background      none

# black
color0   #242424
color8   #4a4a4a

# red
color1   #fc6b83
color9   #fc6b83

# green
color2   #3fa266
color10  #70b489

# yellow
color3   #d2943e
color11  #f1b467

# blue
color4   #81a1c1
color12  #87a6c4

# magenta
color5   #b48ead
color13  #b48ead

# cyan
color6   #88c0d0
color14  #88c0d0

# white
color7   #e4e4e4
color15  #e4e4e4
