# vim:ft=kitty

## name: Xcode WWDC
## author: Apple / iTerm2-Color-Schemes
## license: MIT
## blurb: Xcode WWDC theme. Matches Ghostty's built-in Xcode WWDC.

foreground              #e7e8eb
background              #292c36
selection_foreground    #e7e8eb
selection_background    #494d5c

cursor                  #e7e8eb
cursor_text_color       #292c36

url_color               #8884c5

active_border_color     #8884c5
inactive_border_color   #494d5c
bell_border_color       #bb383a

active_tab_foreground   #e7e8eb
active_tab_background   #292c36
inactive_tab_foreground #7f869e
inactive_tab_background #292c36
tab_bar_background      none

# black
color0   #494d5c
color8   #7f869e

# red
color1   #bb383a
color9   #bb383a

# green
color2   #94c66e
color10  #94c66e

# yellow
color3   #d28e5d
color11  #d28e5d

# blue
color4   #8884c5
color12  #8884c5

# magenta
color5   #b73999
color13  #b73999

# cyan
color6   #00aba4
color14  #00aba4

# white
color7   #e7e8eb
color15  #e7e8eb
