eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/Users/spike/.local/bin/mise activate zsh)"
eval "$(starship init zsh)"

alias bi='brew install'
alias bu='brew uninstall'
alias bs='brew search'
alias bl='brew list'
alias bbd='brew bundle dump --file=~/dotfiles/homebrew/Brewfile --force'

alias df="df -h"
alias cp='cp -i'
alias mv="mv -i"
alias rm='rm -i'

alias ls='eza -F'
alias l="eza -l"
alias la="eza -a"
alias ll="eza -la"
alias lt="ls -lhtrF"
alias l.="ls -lhtrdF .*"
alias lla='ls -la'

alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias config="vim ~/.zshrc"
alias reload="source ~/.zshrc"

alias vi="nvim"
alias vim="nvim"

alias up="brew update && brew upgrade && brew cleanup && mas upgrade && ~/.config/plum/rime-install iDvel/rime-ice:others/recipes/all_dicts"
alias ip="ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'"

# deploy rime input method
# alias rime='/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload'


# Added by Antigravity CLI installer
export PATH="/Users/spike/.local/bin:$PATH"
