# export PATH=$HOME/.nix-profile/bin:$PATH

export PATH="/usr/local/bin:$PATH"

export https_proxy=http://127.0.0.1:6152;export http_proxy=http://127.0.0.1:6152;export all_proxy=socks5://127.0.0.1:6153

# my alias
alias bi='brew install'
alias bu='brew uninstall'
alias bs='brew search'
alias bl='brew list'
alias bbd='brew bundle dump --file=~/dotfiles/homebrew/Brewfile --force'

alias df="df -h"
alias cp='cp -i'
alias mv="mv -i"
alias rm='rm -i'

alias ls='exa -F'
alias l="exa -l"
alias la="exa -a"
alias ll="exa -la"
alias lt="ls -lhtrF"
alias l.="ls -lhtrdF .*"
alias lla='ls -la'

alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias vz="vim ~/.zshrc"
alias sz="source ~/.zshrc"

alias vi="nvim"
alias vim="nvim"

# update app
alias up="brew update && brew upgrade && brew cu -a -y && brew cleanup && mas upgrade && ~/.config/plum/rime-install iDvel/rime-ice:others/recipes/all_dicts"
alias icon="fileicon set /Applications/alacritty.app $HOME/dotfiles/macOSicons/kitty.icns &&
fileicon set /Applications/Figma.app $HOME/dotfiles/macOSicons/Figma.icns &&
fileicon set /Applications/HandBrake.app $HOME/dotfiles/macOSicons/handbrake.icns &&
fileicon set /Applications/GitHub\ Desktop.app/ $HOME/dotfiles/macOSicons/GitHub\ Desktop.icns &&
fileicon set /Applications/AppCleaner.app $HOME/dotfiles/macOSicons/AppCleaner.icns"

# deploy rime inpit 
# alias rime='/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload'

alias ip="ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'"

# reload plugins from nix
source $HOME/.nix-profile/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.nix-profile/share/zsh-z/zsh-z.plugin.zsh

# Set up shell to use Starship
eval "$(starship init zsh)"
