# Font
font_family Berkeley Mono
bold_italic_font auto
font_size 12.0

# Text Cursor
cursor_shape block
cursor_trail 1
cursor_blink_interval 0
shell_integration no-cursor

# Mouse
copy_on_select yes
confirm_os_window_close 1

# Window
window_padding_width 8
placement_strategy center
window_logo_position center

# Tab
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_align center
tab_powerline_style slanted
# 间距稍微留一点，更像独立顶栏
tab_bar_margin_width 8
tab_bar_margin_height 6 0

# Color scheme
# background_opacity 0.88
# macos_blur yes
# background_blur 14
hide_window_decorations no
macos_titlebar_color system

# Advanced
allow_remote_control yes

# OS specific tweaks 
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

# Keyboard shortcuts
# 切换tab
map cmd+t new_tab_with_cwd
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3

# 启动默认布局
enabled_layouts splits

# 右侧新增 pane（左右分屏）
map cmd+d launch --location=vsplit --cwd=current
# 下方新增 pane（上下分屏）
map cmd+shift+d launch --location=hsplit --cwd=current

# 切换焦点
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# ⌘W：先关 split（window），只剩一个时再关 tab
map cmd+w close_window

# tmux 中 Shift+Enter 换行
map shift+enter send_text all \x1b\r


# 标题简洁，不要太多信息
tab_title_template "{title}"
active_tab_title_template "{title}"

# BEGIN_KITTY_THEME
# GitHub Light
include current-theme.conf
# END_KITTY_THEME

shell fish

