[tools]
bun = "latest"
fastfetch = "latest"
gh = "latest"
lazygit = "latest"
node = "25.8.1"
ripgrep = "latest"
yazi = "latest"
tmux = "latest"
eza = "latest"
mas = "latest"
"aqua:neovim/neovim" = "0.10.4"
starship = "latest"
"npm:@antfu/ni" = "latest"
zoxide = "latest"
"npm:playwright" = "latest"
pnpm = "latest"
gum = "latest"
xcodegen = "latest"
swiftlint = "latest"
rust = "stable"
tokei = "14.0.0"
